export default [
  'No justice no peace.',
  `I didn't change, I just woke up.`,
  `Stay Woke.`,
  `My body my choice.`,
  `Real men are feminists.`,
  `Well behaved women seldom make history.`,
  `CoeXisT`,
  `"Nah." - Rosa Parks`,
  `This is what a feminist looks like.`,
  `Rise!`,
  `I Dissent.`,
  `HOPE`,
  `Not me. Us.`,
  `I am once again asking for your financial support.`,
  `Social justice warrior.`,
  `Woke AF.`,
  `#staywoke`,
  `Love is Love.`,
  `Nasty woman.`,
  `Respect our existence or expect our resistance.`,
  `Girl power!`,
  `The future is female.`,
  `Making herstory.`,
  `Nevertheless, she persisted.`,
  `[insert woke caption]`,
  `Save the turtles`,
  `If not know, then when?`,
  `She believed she could, so she did.`,
  `Social justice warrior.`,
  `Women supporting women.`,
  `Stop the war.`,
  `Every day is earth day.`,
  `Reuse. Reduce. Recycle.`,
  `Go Green`,
  `Love animals, eat plants.`,
  `#forthekids`,
  `If you woke up without a goal, go back to sleep.`
]
